[build-system]
requires = ["setuptools>=60.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.flake8]
max-line-length = 88
exclude = ["__pycache__", "build", "dist", "venv"]
